runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /javascript
  static_dir: javascript

- url: /img
  static_dir: img

- url: /js
  static_dir: js

- url: /.*
  script: index.application


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
